'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { leadSchema, type LeadInput } from '@/lib/lead-schema'

const fields = [
  ['name','Nome completo','text'],['company','Empresa','text'],['role','Cargo ou função','text'],['email','E-mail corporativo','email'],['whatsapp','WhatsApp','tel'],['location','Cidade e estado','text'],
] as const
const technicians=['1–4','5–10','11–20','21–30','Mais de 30']
const orders=['Até 50','51–100','101–300','301–500','Mais de 500']
const controls=['WhatsApp','Papel','Planilhas','ERP genérico','Software de ordem de serviço','Combinação de ferramentas']

export function LeadForm(){
 const [status,setStatus]=useState<'idle'|'success'|'error'>('idle')
 const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<LeadInput>({resolver:zodResolver(leadSchema),defaultValues:{consent:false,website:''}})
 const onSubmit=async(data:LeadInput)=>{setStatus('idle');try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error();setStatus('success');reset()}catch{setStatus('error')}}
 return <section id="contato" className="section bg-card"><div className="container-page grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Solicite uma conversa</p><h2 className="section-title">Vamos entender o caminho entre sua operação e o faturamento.</h2><p className="section-copy">Conte um pouco sobre sua equipe. Usaremos essas informações apenas para avaliar a aderência ao programa piloto.</p></div><form onSubmit={handleSubmit(onSubmit)} noValidate className="rounded-2xl border border-border bg-background p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{fields.map(([name,label,type])=><Field key={name} label={label} error={errors[name]?.message}><input {...register(name)} id={name} type={type} aria-invalid={!!errors[name]} className="input" /></Field>)}<SelectField label="Quantidade de técnicos" name="technicians" options={technicians} register={register} error={errors.technicians?.message}/><SelectField label="OS aproximadas por mês" name="monthlyOrders" options={orders} register={register} error={errors.monthlyOrders?.message}/><SelectField label="Controle atual" name="currentControl" options={controls} register={register} error={errors.currentControl?.message} wide/><Field label="Principal dificuldade entre execução e faturamento" error={errors.challenge?.message} wide><textarea {...register('challenge')} id="challenge" rows={4} aria-invalid={!!errors.challenge} className="input resize-none"/></Field><div className="hidden" aria-hidden="true"><label htmlFor="website">Website</label><input {...register('website')} id="website" tabIndex={-1} autoComplete="off"/></div><label className="flex items-start gap-3 sm:col-span-2"><input {...register('consent')} type="checkbox" className="mt-1 size-4 accent-primary"/><span className="text-sm">Concordo em receber contato da Ciclera sobre o programa piloto.</span></label>{errors.consent&&<p className="text-sm text-destructive sm:col-span-2">{errors.consent.message}</p>}<button disabled={isSubmitting} className="min-h-12 rounded-xl bg-primary px-6 font-semibold text-primary-foreground disabled:opacity-60 sm:col-span-2" type="submit">{isSubmitting?'Enviando informações...':'Solicitar conversa'}</button>{status==='success'&&<p role="status" className="rounded-xl bg-active/10 p-4 text-sm font-semibold text-primary sm:col-span-2">Recebemos seus dados. Entraremos em contato para entender melhor sua operação.</p>}{status==='error'&&<p role="alert" className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive sm:col-span-2">Não foi possível enviar agora. Tente novamente ou fale conosco pelo WhatsApp.</p>}</div></form></div></section>
}
function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:React.ReactNode}){return <div className={wide?'sm:col-span-2':''}><label className="mb-2 block text-sm font-medium">{label}</label>{children}{error&&<p className="mt-1 text-sm text-destructive">{error}</p>}</div>}
function SelectField({label,name,options,register,error,wide}:{label:string;name:'technicians'|'monthlyOrders'|'currentControl';options:readonly string[];register:ReturnType<typeof useForm<LeadInput>>['register'];error?:string;wide?:boolean}){return <Field label={label} error={error} wide={wide}><select {...register(name)} id={name} aria-invalid={!!error} className="input"><option value="">Selecione</option>{options.map(x=><option key={x}>{x}</option>)}</select></Field>}
